### ISSUE TITLE
installed, but not recognized in the command line

### ISSUE THREAD

**Issue by vassiki** [choldgraf/gitautopush#1]
I am able to install gitautopush through pip, and load it as a module in python, but it isn't recognized as a command in the terminal.
 
![usage_gitautopush](https://user-images.githubusercontent.com/14996900/33087556-f4270488-ceb8-11e7-88f6-985821cd5379.png)

**Comment by choldgraf** [comment]
hmmm, can you do `gitautopush.__file__` and see if the folder in which it lives is in your bash path?

**Comment by choldgraf** [comment]
(and make sure to restart your terminal window)

**Comment by vassiki** [comment]
Screenshot from a restarted terminal window. the path specified in my bash profile does seem to include the directory where gitautopush was installed. 

![screen shot 2017-11-21 at 12 51 13 pm](https://user-images.githubusercontent.com/14996900/33088165-db9f3726-ceba-11e7-8b14-e99fe8c978bb.png)

**Comment by choldgraf** [comment]
huh, that's weird...can you try running `gitautopush` by calling it
directly, specifying the full path? also confirm that `which gitautopush`
gives no output
--

**Comment by vahtras** [comment]
I have the same problem. it works if I download and pip install from the unpacked tarball but not from pip directly

```
$ virtualenv venv && source venv/bin/activate
Running virtualenv with interpreter /usr/bin/python2
New python executable in /tmp/venv/bin/python2
Also creating executable in /tmp/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
(venv) $ pip install gitautopush
Collecting gitautopush
  Using cached gitautopush-0.3-py2.py3-none-any.whl
Installing collected packages: gitautopush
Successfully installed gitautopush-0.3
(venv) $ which gitautopush
(venv) $ pip install -e /tmp/gitautopush-0.3
Obtaining file:///tmp/gitautopush-0.3
Installing collected packages: gitautopush
  Found existing installation: gitautopush 0.3
    Uninstalling gitautopush-0.3:
      Successfully uninstalled gitautopush-0.3
  Running setup.py develop for gitautopush
Successfully installed gitautopush
(venv) $ which gitautopush
/tmp/venv/bin/gitautopush

```

**Comment by choldgraf** [comment]
I believe this was a bug in the `flit` setup I was using to publish wheels to `pip`. I think it's fixed now! Give it a shot and let me know if it works.

**Comment by vassiki** [comment]
yes, I'm able to use it seamlessly now, thanks!

**Comment by choldgraf** [comment]
🎉
